# Generated by Django 4.2.1 on 2023-05-13 15:27

import contact.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(max_length=255, validators=[contact.utils.validate_mobile_number])),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Infos',
                'db_table': 'contact_name',
            },
        ),
    ]
